version: '3'

services:
  backend:
    build: .
    ports:
      - 8080:8080
    restart: always
    depends_on: 
      - db
    networks:
      - spring
      - spring-postgres
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "order"
    networks:
      - spring
      - spring-postgres
networks:
  spring: {}
  spring-postgres: {}